config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    resource :static_pages, only: [:home, :help] do
      get "/home", to: "static_pages#home"
      get "/help", to: "static_pages#help"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  private
  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t("static_pages.title")
    page_title.blank? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layout.header.logo"), home_static_pages_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("layout.header.home"), home_static_pages_path %></li>
        <li><%= link_to t("layout.header.help"), help_static_pages_path %></li>
        <li><%= link_to t("layout.header.login"), "#" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide :title, t("static_pages.help.title") %>
<div class="center jumbotron">
  <h1><%= t("static_pages.help.welcome")%></h1>
  <p>
    <%= t("static_pages.help.content1")%>
    <%= link_to t("static_pages.help.content2"), Settings.url.rails_home %>
    <%= t("static_pages.help.content3")%>
    <%= link_to t("static_pages.help.content4"), Settings.url.rails_help %>
    <%=t("static_pages.help.content5")%>
    <%= link_to t("static_pages.help.content6_html"), Settings.url.rails_book %>
    <%= t("static_pages.help.content7")%>
  </p>
</div>

app/views/static_pages/home.html.erb
<% provide :title, t("static_pages.home.title") %>
<div class="center jumbotron">
  <h1><%= t("static_pages.home.welcome")%></h1>
  <h2>
    <%= t("static_pages.home.content1")%>
    <%= link_to t("static_pages.home.content2"), Settings.url.rails_home %>
    <%= t("static_pages.home.content3")%>
  </h2>
  <%= link_to t("static_pages.home.sign_up"), "#", class: "btn btn-lg btn-primary" %>
</div>